services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /code/node_modules
      - .:/code
    restart: always
    ports:
      - 3000:3000
